- src/components/common/Button.stories.ts
- src/components/common/Button.tsx
- src/components/common/types.d.ts
- ダッシュボード用のstart workoutボタン追加
- ダッシュボードにstart workoutボタンを表示させたいから
#18 
Closes #
#15
#17 
- Buttonコンポーネントにstart workoutを追加
> [Feat] ダッシュボード用のstart workoutボタン追加

- src/app/api/exercises/route.test.ts
- src/app/api/exercises/route.ts
トレーニング種目用のAPI構築
- トレーニング追加の際の種目一覧表示
- トレーニング種目のCRUD操作機能
Closes #65 
-`/exercises`ルート作成
- CRUD操作のための各HTTP methods追加 `GET` `POST` `PATCH` `DELETE`
> [Feat] Exercises API 追加

- src/app/dashboard/page.tsx
- src/app/signin/page.tsx
- src/app/signup/page.tsx
- src/components/common/Button.tsx
- src/components/common/Form.tsx
ログイン/サインアップページからダッシュボードページへの遷移
ユーザ認証後にダッシュボードページへの遷移処理があるため
Closes #75 
- `/dashboard`ルートの作成
- `<Form />`, `<Button />`のonClick用props受け取り追加
- ログイン/サインアップページからフォームへのリダイレクト関数(ログイン→ダッシュボード)受け渡し
> [Feat] ログイン/サインアップページからダッシュボードページへの遷移

- src/app/api/login/route.ts
- src/app/api/signup/route.ts
- src/utils/validateLoginUser.test.ts
- src/utils/validateLoginUser.ts
- src/utils/validateSignupUser.test.ts
- src/utils/validateSignupUser.ts
Signup/Login APIへのauth処理用のutil関数
FE側のauth処理のコードを読みやすく
Closes #87 
- `/api/signup`のリクエストボディの値取得修正
- `/api/signup`用のutil関数`validateSignupUser`を作成
- `/api/login`のリクエストボディの値取得修正
- `/api/login`用のutil関数`validateLoginUser`を作成
> [Util] Signup/Login用のutil関数作成

- src/app/dashboard/page.tsx
- src/app/layout.tsx
- src/app/signin/page.tsx
- src/components/common/Form.tsx
- src/components/common/Input.tsx
- src/components/common/types.d.ts
ログイン後にアプリ全体でログインユーザ情報を使用できるようにする
ログイン認証後にユーザごとのトレーニング履歴などの個別データを表示する必要がある
Closes #92
- ログイン後にアプリ全体で情報共有のためアプリ全体を`LoginUserContext`でラップ
- ログインフォームのインプット値管理のため関連するcomponentの修正
- `/signin`でのログイン認証
> [Feat] ログイン認証後のアプリ全体でのユーザ情報共有

- src/components/dashboard/History.stories.ts
- src/components/dashboard/History.tsx
- src/components/dashboard/types.d.ts
- src/components/index.ts
ログインユーザのトレーニング履歴を表示するUI
ダッシュボードページでログインユーザのトレーニング履歴を表示するため
Closes #94 
- `<History />`作成
- `<History />`をコンポーネント用エントリーポイントに追加
> [Component] Historyコンポーネント追加

- src/app/api/histories/route.ts
- src/app/dashboard/page.tsx
`/dashboard`でのトレーニング履歴表示
ダッシュボードペーいにトレーニング履歴表示機能をを実装する
Closes #96 
- `/histories`APIのエラーメッセージ修正
- `/histories`APIのクエリパラメータ取得バグ修正
- `/dashboard`にログインユーザのトレーニング履歴表示
> [Feat] ダッシュボードページにログインユーザのトレーニング履歴を表示

- src/app/signin/page.tsx
- src/app/signup/page.tsx
- src/components/common/Form.tsx
- Formコンポーネントが画面の中央に表示されるように修正
- signin/signup画面のInputとButtonが左端に表示されていたから
Closes #
- Formコンポーネント内でInputフォームとButtonが真ん中に表示されるようにcss変更
> Formコンポーネントが画面の中央に表示されるように修正

- src/app/dashboard/page.tsx
- src/app/workout/page.tsx
- src/components/common/NoAuthUserRedirection.tsx
- src/components/index.ts
非認証ユーザがユーザページ(`/dashboard`, `/workout`)へアクセスした時にサインインページへリダイレクトされる機能追加
登録ユーザのみアプリ機能を利用できる仕様にするため
Closes #97 
- リダイレクト用のコンポーネント作成
- `/dashboard`のページコンポーネントをラップ
- `/workout`のページコンポーネントをラップ
@yurihoka 
コンポーネントは`components/common`に作成しましたが、UIではないのでstoriesファイルを作っていないです
> [Feat] 非認証ユーザのユーザページアクセス時のサインインページ強制リダイレクト

- src/components/common/Button.tsx
- StartWorkoutボタンをクリックしてWorkoutページに遷移させる
- StartWorkoutボタンをクリックしたら、Workoutページに遷移する
Closes #
- Buttonコンポーネントの`startworkout`にonClick追加
> [Feat] StartWorkoutボタンをクリックしてWorkoutページに遷移させる

- src/app/signup/page.tsx
Signupページでの新規ユーザ登録処理の追加
ユーザ登録機能実装のため
Closes #112 
- `/signup`ページにフォーム内容保持のためのstateを作成
- Signupボタン押下時にユーザ情報stateを使ってSignup APIへのAPIコール追加
> [Feat] Signupページでの新規ユーザ登録処理追加

- src/app/(auth)/signin/page.tsx
- src/app/(auth)/signup/page.tsx
サインインページ内にサインアップページへのリンクを追加
ユーザが最初にアクセスするページはログインページだが、そのページから未登録ユーザがサインアップするためにアクセスするサインアップページへの動線が無かった
Closes #114 
- サインインページ内にリンクを作成
- サインアップのページコンポーネントにあった不要なマージメッセージを削除
> [Feat] サインインページ内にサインアップページへのリンクを追加

- next.config.mjs
`/`へアクセス時に`/signin`へ自動リダイレクトされる設定追加
`/`は現在何もコンテンツがないので、ユーザの利便性的にsigninへアクセスする方が良い
Closes #118 
- nextの設定ファイルに自動リダイレクト設定を追記
> [Feat] `/` → `/signin`への自動リダイレクト設定追加

- src/components/common/Button.tsx
WorkoutページのCancel Workoutボタンの色変更
Workoutページ内のボタンが全て同色で見辛いため
Closes #120 
- `<Button />`のCancel ver.のスタイル変更
> [Fix] Cancel Workoutボタンの色変更

- src/app/(auth)/signin/page.tsx
- src/app/(auth)/signup/page.tsx
- src/components/common/Button.tsx
- src/components/common/Form.tsx
- src/components/common/Input.tsx
- src/utils/validateLoginUser.test.ts
- src/utils/validateLoginUser.ts
- src/utils/validateSignupUser.test.ts
- src/utils/validateSignupUser.ts
Signup/Signinページのemail, password入力のバリデーション処理追加
エラー防止。入力値にスペースなどエラー発生の原因になる文字が入力される可能性があるため。
Closes #111 
- 入力フォーム`<Form />`の入力値管理をstateから`react-hook-form`に変更
- Email/Passwordの入力フォームにバリデーションを設定
- Utils関数と`<Input />`のリファクタ
> [Feat] ユーザ認証フォームのインプットバリデーション

- src/components/common/Form.tsx
Signin/Signupページのユーザ認証エラーメッセージ表示
認証失敗時に理由を提示するとユーザが使いやすい
Closes #124 
- `<Form />`にエラーメッセージ用のstateを追加
-  フォーム入力値認証またはログイン情報認証のどちらかエラーメッセージを表示
> [Feat] Signin/Signupページのユーザ認証エラーメッセージ表示

- src/app/(user)/workout/page.tsx
- src/components/workout/Exercise.tsx
Workoutページ上の記録編集のためトレーニング種目削除のボタン追加
トレーニング追加はできるが削除はできなかったため
Closes #129 
- 各種目のレコードに削除用ボタンを追加
> [Feat] トレーニング記録の種目削除ボタン追加

- src/app/api/histories/route.test.ts
- src/app/api/histories/route.ts
Histories APIに過去トレーニングデータを更新/削除するメソッドを追加
トレーニングデータのCRUD操作のUD実装のため
Closes #132 
- Histories API `/api/histories/route.ts`に`PATCH`追加
- Histories API `/api/histories/route.ts`に`DELETE`追加
> [Feat] Histories APIに更新/削除追加

- src/app/(user)/dashboard/page.tsx
- src/app/(user)/layout.tsx
- src/app/(user)/workout/edit/page.stories.ts
- src/app/(user)/workout/edit/page.tsx
- src/app/(user)/workout/page.tsx
- src/components/common/Button.tsx
- src/components/common/Navbar.tsx
- src/components/common/types.d.ts
過去に登録したトレーニング記録を更新または削除するページ作成
CRUD機能のうちUDが未実装のため
Closes #131
- 更新/削除用ページ`/workout/edit`を追加
- ダッシュボードページからの更新ページへのリンク追加
> [Feat] 過去トレーニング記録の更新/削除機能ページ追加

- src/app/(user)/workout/edit/page.tsx
- src/app/(user)/workout/formatSubmitData.ts
- src/app/(user)/workout/page.tsx
デプロイエラー解消のためworkoutページ内の関数を移行
Vercelデプロイができないため
Closes #
- `/workout`配下のページにて共通利用している`formatSubmitData`を移行
> [Fix] デプロイエラー解消のためworkoutページ内の関数を移行
